E_Com/E_Com/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('E_Comm_User.urls')),
    path('inventory/', include('Inventory.urls')),
    path('system/', include('SysHealth.urls'))
]

E_Com/E_Comm_User/urls.py
from django.urls import path

from . import views

app_name = 'E_Comm_User'

urlpatterns = [
    path('', views.login, name='home'),
    path('home/', views.home, name='home'),
    path('register/', views.signup, name='signUp'),
    path('login/', views.login, name='login'),
    path('admin_home/', views.admin_home, name='admin_home'),
    # path('placements/', views.home, name='home'),
    path('logout/', views.logout, name='logout'),
]

E_Com/templates/about.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %}

<section class="section">
    <section class="container">

        <article class="card">
            <div class="card-content">
                <h4>About</h4>
                <p class="custom-font-1">This application was built as a side project, in order to learn how to design
                    and build a bidding system from scratch. The theme is based on capital raising for companies. It
                    includes an auth system, marketplace, companies, placements,
                    dashboard, mobile friendly design. I used Django mainly, to develop this application.</p>
            </div>
        </article>
        <article class="card">
            <div class="card-content">
                <h4>Available Routes</h4>
                <ul class="collection custom-font-1">
                    <li class="collection-item"><span class="chip">/</span> The home page. Contains news.</li>
                    <li class="collection-item"><span class="chip">about/</span> Holds details about the application.
                    </li>
                    <li class="collection-item"><span class="chip">register/</span> Allows users to register an account
                    </li>
                    <li class="collection-item"><span class="chip">login/</span> Allows users to login to an account
                    </li>
                    <li class="collection-item"><span class="chip">logout/</span> Allows users to logout and clear their
                        session
                    </li>

                    <li class="collection-item"><span class="chip">marketplace/</span> Listing of placements from
                        various companies.
                    </li>

                    <li class="collection-item"><span class="chip">marketplace/slug/</slug></span> Detailed view for a
                        placement within the marketplace.
                    </li>
                    <li class="collection-item"><span class="chip">my-bids/</span> User scope bid summary for available
                        placements.
                    </li>
                    <li class="collection-item"><span class="chip">dashboard/</span> Basic analytics and animated charts
                        for the database.
                    </li>

                </ul>
            </div>
        </article>


        <article class="card">
            <div class="card-content">
                <h4>Features and specs</h4>
                <ul class="collection custom-font-1">
                    <li class="collection-item">Authentication system - users can login, register and logout, passwords
                        are securely hashed with PBKDF2 method.
                    </li>
                    <li class="collection-item ">Certain routes are protected with a login required decorator, giving
                        security to administrators/owners. Unregistered users are prompted to login on the home page.
                    </li>
                    <li class="collection-item">Dashboard include dynamic and animated charts to draw insights from
                        database.
                    </li>
                    <li class="collection-item">Data is modelled in ORM and automatically generated by Django to RDBS of
                        choice.
                    </li>
                    <li class="collection-item">Data included in application is randomly generated using the
                        <code>faker</code> library
                    </li>
                    <li class="collection-item">App uses materialize css framework borrowing from Google's material
                        design principles
                    </li>
                    <li class="collection-item">App developed mainly in Django framework and Javascript.</li>
                </ul>
            </div>
        </article>

    </section>
</section>

{% include 'footer.html' %} {% endblock content %}

E_Com/templates/admin_home.html
{% extends 'base.html' %} {% block content %} {% include 'admin_nav.html' %} {% load static %}

<section class="section">
    <section class="container">
        <div class="card z-depth-2">
            <div class="card-content">

                <h5>The Marketplace</h5>

                <p class="custom-font-1">Please check & confirm new biddings.</p>
                <a href="/dashboard" class="btn waves-effect waves-light pink" style="margin-top: 1rem;">
                    <i class="material-icons left"></i>View Dashboard</a>
                <a href="/confirmbiddings" class="btn waves-effect waves-light pink" style="margin-top: 1rem;">
                    <i class="material-icons left"></i>Check new biddings</a>
                <img class="responsive-img fade-in"
                     src="{% static 'How-to-Start-an-Online-Auction-Marketplace-Core-Features.jpg' %}" alt="">
            </div>
        </div>
    </section>
</section>
<footer class="page-footer indigo darken-2">
    <div class="container center custom-font-1">
        © 2019 Copyright Text
    </div>
</footer>
{% endblock content %}

E_Com/templates/admin_nav.html
<nav>
    <div class="nav-wrapper indigo darken-2">
        <div class="container">


            {% if user.is_authenticated %}
            <a href="#" data-target="mobile-demo" class="sidenav-trigger waves-effect waves-light"><i
                    class="material-icons">menu</i></a>

            <ul class="left hide-on-med-and-down">
                <li><a href="{% url 'E_Comm_User:home' %}">Home</i></a></li>


                <li><a href="/createbiddings">Create Service</a></li>
                <li><a href="/admin/app/placementbid/">View Biddings</a></li>
                <li><a href="">Dashboard</a></li>

            </ul>
            {% else %}
            <a href="{% url 'E_Comm_User:home' %}" class="brand-logo" style="font-size: 1.3rem;">
                <strong>BIDDING PLATFORM</strong></a>
            {% endif %}


            <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a class="btn-small waves-effect waves-light grey darken-4" href="{% url 'E_Comm_User:logout' %}">Logout</a>
                </li>
                <li>Logged in as <strong>{{ user.username }}</strong></li>
                {% else %}
                <li>
                    <a class="btn-small waves-effect waves-light pink" href="{% url 'E_Comm_User:register' %}">
                        Register
                    </a>
                </li>
                <li>
                    <a class="btn-small waves-effect waves-light pink" href="{% url 'E_Comm_User:login' %}">
                        Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

E_Com/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <link href="https://fonts.googleapis.com/css?family=Literata|Raleway|Montserrat|Nunito&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <title>Deebaco Task</title>

    <style>
      p {
        margin-top: 0.5rem !important;
        margin-bottom: 0.5rem!important;
      }

      img {
        margin-top: 1em;
        padding: 4%;
      }

      .custom-font-1 {
        font-family: 'Literata', serif;
      } 

      h1, h2, h3, h4, h5, h6 {
        margin-top: .5em !important;
        font-family: 'Nunito', sans-serif;
        font-weight: bold;
      }

      body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      main {
        flex: 1 0 auto;
      }
        
      input:focus {
        border-bottom: 1px solid deeppink !important;
        box-shadow: 0 1px 0 0 deeppink !important;
      }


      /* ----------------------------------------------
 * Generated by Animista on 2019-7-21 13:37:41
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

.fade-in {
	-webkit-animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in 1s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}




    </style>
</head>
<body class="grey lighten-4">
{% block content %}
{% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function(){
      var elems = document.querySelectorAll('.sidenav');
      var instances = M.Sidenav.init(elems);
    })

</script>
</body>
</html>

E_Com/templates/bid-summary.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}

<section class="section">
    <section class="container">
        <div class="card">
            <div class="card-content">
                <h4>Your bid summary</h4>
                <table class="table responsive-table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Bid status</th>
                        <th>Company Name</th>
                        <th>Timestamp</th>
                        <th>$ Bidded</th>

                    </tr>
                    </thead>

                    <tbody>
                    {% for b in bids %}
                    <tr>
                        <td>{{ b.id }}</td>
                        <td>{% if b.confirmed %}<span class="chip">Confirmed</span>{%else%} <span
                                class="chip indigo darken-2 white-text">Unconfirmed</span> {%endif%}
                        </td>
                        <td>{{ b.placement.placement_company }}</td>
                        <td>{{ b.placementbid_created }}</td>
                        <td>{{ b.offer}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <a href="{% url 'app:confirm-bids' %}" style="margin-top: 1rem;"
                   class="btn waves-light waves-effect pink">Confirm Bids</a>
            </div>
        </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

E_Com/templates/confirmbiddings.html
{% extends 'base.html' %} {% block content %} {% include 'admin_nav.html' %} {% load static %}
<script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>


<section class="section">
    <section class="container">
        <div class="card z-depth-2">
            <div class="card-content">

                <table id="result_list" class="sortable">
                    <thead>
                    <tr>


                        <th scope="col" class="sortable column-user">


                            <div class="text">User</div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col" class="sortable column-offer">


                            <div class="text">Offer</div>
                            <div class="clear"></div>
                        </th>

                        <th scope="col" class="sortable column-placement">


                            <div class="text">Placement</div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col" class="sortable column-offer">


                            <div class="text">BID Id</div>
                            <div class="clear"></div>
                        </th>
                        <th scope="col" class="action-checkbox-column">

                            <div class="text"><span>Confirmed</span></div>
                            <div class="clear"></div>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {%for p in context %}
                    <tr>
                        <th class="field-user nowrap"><a href="/confirmbid/{{ p.id}}/">{{ p.user__username }}</a></th>
                        <td class="field-offer">{{ p.offer }}</td>
                        <td class="field-placement nowrap">{{ p.placement__placement_title }}</td>
                        <td class="field-placement nowrap">{{ p.id }}</td>
                        <td class="field-placement nowrap">{{ p.confirmed }}</td>

                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</section>

<footer class="page-footer indigo darken-2">
    <div class="container center custom-font-1">
        © 2019 Copyright Text
    </div>
</footer>
{% endblock content %}

E_Com/templates/home.html
{% extends 'base.html' %} {% block content %} {% include 'nav.html' %} {% load static %}

<section class="section">
    <section class="container">
        {% if user.is_authenticated == False %}
        <div class="card z-depth-2">
            <div class="card-content">
                <h5>Notice</h5>
                <p class="custom-font-1">You must have a registered account and be logged in, in order to view and place
                    bids within our marketplace.</p>
            </div>
        </div>
        {% endif %}

        <div class="card z-depth-2">
            <div class="card-content">

                <h5>The Marketplace</h5>

                <p class="custom-font-1">Welcome to bidding platform login & visit marketplace.</p>

                <a href="/marketplace" class="btn waves-effect waves-light pink" style="margin-top: 1rem;">
                    <i class="material-icons left">store</i>visit marketplace</a>
                <img class="responsive-img fade-in"
                     src="{% static 'How-to-Start-an-Online-Auction-Marketplace-Core-Features.jpg' %}" alt="">
            </div>
        </div>


        <div class="card z-depth-2">
            <div class="card-content">

                <h5>Get your new honda.</h5>
                <!--p class="custom-font-1"><br>Start bidding.</p-->
                <img class="responsive-img fade-in" src="{% static '2020-honda-city-rear-1-1068x624.jpg' %}" alt="">
            </div>
        </div>

        <div class="card z-depth-2">
            <div class="card-content">
                <h5>
                    Get your skoda
                </h5>
                <img class="responsive-img fade-in"
                     src="{% static 'skoda-slavia-revealed-check-images-details-1.jpg' %}" alt="">
            </div>
        </div>


    </section>
</section>
<footer class="page-footer indigo darken-2">
    <div class="container center custom-font-1">
        © 2019 Copyright Text
    </div>
</footer>
{% endblock content %}

E_Com/templates/login.html
{% extends 'base.html' %} {% block content %}
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l8 m12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form action="" method="POST" class="form">
                                {% csrf_token %}
                                <h5>Login page</h5>
                                <div class="input-field">
                                    <label for="username" class="label">
                                        Username
                                    </label>
                                    <input id="username" type="text" name="username">
                                </div>
                                <div class="input-field">
                                    <label for="password" class="label">
                                        Password
                                    </label>
                                    <input id="password" type="password" name="password">
                                </div>
                                <div class="input-field">
                                    <button style="margin-top: 1rem;" class="btn waves-effect waves-light pink"
                                            type="submit">Login
                                    </button>
                                </div>
                                <p>Don't have an account? click <a href="{% url 'E_Comm_User:signUp' %}"
                                                                   style="margin-top: 1rem;" type="a">here</a> to
                                    register.</p>

                            </form>
                        </div>
                    </div>

                </div>
            </div>

        </section>

    </section>
</main>
{% include 'footer.html' %} {% endblock content %}

E_Com/templates/nav.html
<nav>
    <div class="nav-wrapper indigo darken-2">
        <div class="container">


            {% if user.is_authenticated %}
            <a href="#" data-target="mobile-demo" class="sidenav-trigger waves-effect waves-light"><i
                    class="material-icons">menu</i></a>
            <!--ul class="left hide-on-med-and-down">
                   <li><a href="{% url 'E_Comm_User:home' %}"><i class="material-icons">home</i></a></li>


            </ul-->
            <ul class="left hide-on-med-and-down">
                <li><a href="{% url 'E_Comm_User:home' %}"><i class="material-icons">home</i></a></li>
                <li><a href="/marketplace">Store</a></li>
                <li><a href="/my-bids">View Bids</a></li>
                <li><a href="/about">Help</a></li>
                <!--li><a href="/dashboard">Dashboard</a></li-->

            </ul>
            {% else %}
            <a href="{% url 'E_Comm_User:home' %}" class="brand-logo" style="font-size: 1.3rem;">
                <strong>BIDDING PLATFORM</strong></a>
            {% endif %}


            <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a class="btn-small waves-effect waves-light grey darken-4" href="{% url 'E_Comm_User:logout' %}">Logout</a>
                </li>
                <li>Logged in as <strong>{{ user.username }}</strong></li>
                {% else %}
                <li>
                    <a class="btn-small waves-effect waves-light pink" href="{% url 'E_Comm_User:register' %}">
                        Register
                    </a>
                </li>
                <li>
                    <a class="btn-small waves-effect waves-light pink" href="{% url 'E_Comm_User:login' %}">
                        Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<ul class="sidenav" id="mobile-demo">

    {% if user.is_authenticated %}
    <ul class="left hide-on-med-and-down">
        <li><a href="{% url 'E_Comm_User:home' %}"><i class="material-icons">home</i></a></li>
        <li><a href="/marketplace">Store</a></li>
        <li><a href="/my-bids">View Bids</a></li>
        <li><a href="/about">Help</a></li>
        <!--li><a href="/dashboard">Dashboard</a></li-->

    </ul>

    <li><a class="btn-small waves-effect waves-light grey darken-4" href="/logout">Logout</a></li>
    {% else %}
    <a href="{% url 'E_Comm_User:home' %}" class="brand-logo" style="font-size: 1.3rem;">
        <strong>BIDDING PLATFORM</strong></a>
    <li><a class="btn-small waves-effect waves-light pink" href="/register">
        Register</a>
    </li>
    <li><a class="btn-small waves-effect waves-light pink" href="/login">
        Login</a>
    </li>
    {% endif %}
</ul>

E_Com/templates/placement_detail.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}


<section class="section">
    <section class="container">
        <div class="card">
            <div class="card-content">
                <h5>{{ placement.placement_title }}</h5>
                <p class="chip indigo white-text">{{ placement.placement_company }}</p>
                <p>{{placement.placement_company.company_description}}</p>

                <p class="grey-text">Placement information was added on: {{ placement.placement_created }}</p>
                <p class="grey-text">Placement information was updated on: {{ placement.placement_modified }}</p>

            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <form action="" method="POST" class="form">
                    {% csrf_token %}
                    <h5>Bidding Details</h5>
                    <!--label for="">
                        Share Quantity
                    </label>
                    <input name="quantity" required id="quantity" type="number" min=1-->
                    <label for="">
                        Amount (Rupees)
                    </label>
                    <input name="amount" required id="amount" type="number" min=1>
                    {% for b in bid_exist %}
                    <label for="">
                        {{ b }}
                    </label>
                    {% endfor %}
                    <button type="submit" style="margin-top: 1rem;" class="btn pink waves-effect waves-light">Submit
                        Bid
                    </button>
                </form>
            </div>
        </div>

        <!--div class="card">
             <div class="card-content">
                 <h5>Summary</h5>
                 <ul class="collection">
                     <li class="collection-item">Number of shares (#)
                         <span class="secondary-content" id='span-shares'></span>
                     </li>
                     <li class="collection-item">Total Amount Bidded ($)
                             <span class="secondary-content" id='span-amount'></span>
                     </li>
                     <li class="collection-item">Average Bid Per Share ($)
                             <span class="secondary-content" id='span-average'></span>
                     </li>
                 </ul>
             </div>
         </div-->
    </section>
</section>


{% include 'footer.html' %}

<script>

var display_amount = document.getElementById('span-amount');
var display_shares = document.getElementById('span-shares');
var display_average = document.getElementById('span-average');

var quantity_input = document.getElementById('quantity');
var amount_input = document.getElementById('amount');

var amount;
var quantity;
var average;

change_summary = () => {
    amount = amount_input.value;
    quantity = quantity_input.value;
    
    display_amount.innerText = `${amount}`;
    display_shares.innerText = `${quantity}`;

    if ((amount.length > 0) & (quantity.length > 0)) {
        average = Math.round(amount / quantity);
        display_average.innerText = `${average}`;
    }

}

amount_input.addEventListener('change', change_summary)
quantity_input.addEventListener('change', change_summary)


</script>
{% endblock content %}


<!-- 
placement_title = models.CharField(max_length=255)
placement_slug = models.SlugField()
placement_company = models.ForeignKey(Company, on_delete=models.CASCADE)


placement_created = models.DateTimeField(auto_now_add=True)
placement_modified = -->

E_Com/templates/placements.html
{% extends 'base.html' %}

{% block content %}
{% include 'nav.html' %}


{% load static %}

<section class="section">
    <section class="container">

        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <h4>Welcome to the marketplace</h4>
                    <p>Explore placements by various listed companies</p>
                    <img src="{% static 'ishant-mishra-1349434-unsplash.jpg' %}" alt="" class="responsive-img fade-in">
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-content">
                <table class="table responsive-table">
                    <thead>
                    <tr>

                        <th>Open Services</th>
                        <!--th>Company</--th-->
                        <th>Added</th>
                        <!--th>Modified</th-->
                        <th>View Details</th>
                    </tr>
                    </thead>

                    <tbody>
                    {%for p in placements %}
                    <tr>

                        <td>{{ p.placement_title }}</td>
                        <!--td><span class="chip indigo white-text">{{ p.placement_company }}</span></td-->
                        <td>{{ p.placement_created }}</td>
                        <!--td>{{ p.placement_modified }}</td-->
                        <td><a href="{% url 'app:placement-detail' p.placement_slug %}" style="margin-top: 1rem;"
                               class="btn pink waves-effect waves-light">View Details</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <ul class="pagination center">
                    {% if placements.has_previous %}
                    <li class="waves-effect"><a href="?page={{placements.previous_page_number}}">{{
                        placements.previous_page_number}}</a></li>
                    {% endif %}

                    <li class="active indigo"><a href="#!">{{placements.number}}</a></li>

                    {% if placements.has_next %}
                    <li class="waves-effect"><a href="?page={{placements.next_page_number}}">{{
                        placements.next_page_number}}</a></li>
                    {% endif %}
                </ul>

            </div>
        </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

E_Com/templates/register.html
{% extends 'base.html' %} {% block content %}
<main>
    <section class="section">
        <section class="container">
            <div class="row">
                <div class="col l12 s12">
                    <div class="card">
                        <div class="card-content">
                            <form method="post">
                                {% csrf_token %}
                                <table>
                                    {{ form.as_table }}
                                    <tr>
                                        <td></td>
                                        <td><input type="submit" name="submit" value="Register"/></td>
                                    </tr>
                                </table>
                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</main>
{% include 'footer.html' %} {% endblock content %}